### ISSUE TITLE
Cannot get sendgrid / devise to work with Heroku 

### ISSUE THREAD

**Issue by Heeney** [jordanhudgens/enterpriseape#1]

**Comment by jordanhudgens** [comment]
Did you figure out the issue? I saw that you closed it.

From:  Heeney
Reply-To:  jordanhudgens/enterpriseape
Date:  Monday, August 17, 2015 at 12:06 AM
To:  jordanhudgens/enterpriseape
Subject:  [enterpriseape] Cannot get sendgrid / devise to work with Heroku  (#1)

Hi Jordan,
Just finished your tutorial and it is fantastic but unfortunately I cannot get the sign up feature to work once I have the app on Heroku!
When entering info in sign up and clicking the sign up button I get the Something went wrong Heroku message. 

The Heroku logs shows me : Net::SMTPAuthenticationError (535 Authentication failed: account disabled)

Would you have any idea how to fix?? I have been trolling the internet for hours! its now 6am :-(

Thanks Jordan

**Comment by danwjohnson** [comment]
I did figure it out...but it wasn't me that closed it.  I don't remember
what I did to correct the issue.

Thanks so much for following up with me!!!

Dan

**Comment by Heeney** [comment]
Hey Jordan,

Sorry for the delay and I really appreciate you getting back to me! Really
above and beyond.
Unfortunately I could solve the issue and in the end had to bypass devise
and send grid functionality but I am still currently working on the
project.

I did close the issue as I didn't realize that it would appear as a global
issue on GitHub and didn't want to show as an issue on your GitHub project.
Sorry I'm new to Git :-)

I actually have two issues.
One is the send grid functionality doesn't work once deploying to Heroku.
Although the pages appear fine , once adding an email and desired password
into the Sign in page and clicking OK Heroku displays the
"Something went wrong page". Through the Server log I can see that the
email is sent but then rolled back, I get a 500 server error and
Authentication failed - Account disabled.

Also , the issue which you resolved through the tutorial in displaying the
customer name rather then the employee ID this issue although working
locally and displaying the name fine but once deployed to Heroku the page
doesn't appear , showing a name method error. I believe this is due to the
employee.name, change.

Again really appreciate your help Jordan and your Tutorial is fantastic !
really clear and concise and enjoyable to follow. I'm studying RoR as part
of my cloud computing course in college and find your tutorial really
compliments my learning's and desire to become competent at ruby on rails .

Thanks for all your work, appreciate any feedback, Have a great weekend!

Sean

**Comment by jordanhudgens** [comment]
@Heeney Thanks for the detailed explanation, below is how I would fix the issues:
- Move from Sendgrid to Mandrill, Sendgrid has become difficult to work with for free accounts so I've been moving all of my open source work to Mandrill. Here is a link on how to integrate Mandrill [Mandrill Integration](https://devcenter.heroku.com/articles/mandrill)
- For the name error, it sounds like you have some data missing in your database, if you try calling the `name` attribute and don't have a name for each record it will throw a nil error. To fix it you can either add a nil guard, such as doing something like: `model.name if model.name` or you could go through and remove any records that don't have a name value. For a production application you would want to incorporate a validation to ensure that no one would be able to create a record without a name.
